# Generated by Django 5.1.2 on 2024-10-27 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='password',
            old_name='name',
            new_name='app_name',
        ),
        migrations.RenameField(
            model_name='password',
            old_name='username',
            new_name='category',
        ),
    ]
