# Generated by Django 5.1.2 on 2024-11-11 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0002_rename_name_password_app_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='password',
            old_name='notes',
            new_name='tags',
        ),
    ]
